<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#列表" data-toc-modified-id="列表-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>列表</a></span></li><li><span><a href="#数组的创建★" data-toc-modified-id="数组的创建★-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>数组的创建★</a></span></li><li><span><a href="#查看数组结构" data-toc-modified-id="查看数组结构-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>查看数组结构</a></span></li><li><span><a href="#查看数组类型" data-toc-modified-id="查看数组类型-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>查看数组类型</a></span></li><li><span><a href="#查看数组的大小" data-toc-modified-id="查看数组的大小-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>查看数组的大小</a></span></li><li><span><a href="#更改数组的结构" data-toc-modified-id="更改数组的结构-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>更改数组的结构</a></span></li><li><span><a href="#arange函数" data-toc-modified-id="arange函数-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>arange函数</a></span></li><li><span><a href="#linspace函数——返回等差数组" data-toc-modified-id="linspace函数——返回等差数组-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>linspace函数——返回等差数组</a></span></li><li><span><a href="#logspace函数——返回等比数列" data-toc-modified-id="logspace函数——返回等比数列-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>logspace函数——返回等比数列</a></span></li><li><span><a href="#创建特殊的数组" data-toc-modified-id="创建特殊的数组-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>创建特殊的数组</a></span></li><li><span><a href="#生成随机数" data-toc-modified-id="生成随机数-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>生成随机数</a></span></li><li><span><a href="#一维数组的索引和切片" data-toc-modified-id="一维数组的索引和切片-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>一维数组的索引和切片</a></span></li><li><span><a href="#多维数组的索引和切片★" data-toc-modified-id="多维数组的索引和切片★-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>多维数组的索引和切片★</a></span></li><li><span><a href="#改变数组的形状" data-toc-modified-id="改变数组的形状-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>改变数组的形状</a></span></li><li><span><a href="#数组的拼接" data-toc-modified-id="数组的拼接-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>数组的拼接</a></span></li><li><span><a href="#np.any-、np.all" data-toc-modified-id="np.any-、np.all-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>np.any 、np.all</a></span></li><li><span><a href="#广播★" data-toc-modified-id="广播★-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>广播★</a></span></li><li><span><a href="#排序" data-toc-modified-id="排序-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>排序</a></span></li><li><span><a href="#np.multiply（）、np.dot（）和星号（*）三种乘法运算的区别★" data-toc-modified-id="np.multiply（）、np.dot（）和星号（*）三种乘法运算的区别★-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>np.multiply（）、np.dot（）和星号（*）三种乘法运算的区别★</a></span></li><li><span><a href="#几个重要的函数" data-toc-modified-id="几个重要的函数-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>几个重要的函数</a></span></li></ul></div>

In [1]:
import numpy as np

## 定义list

In [2]:
li = [1, 'a', 1.34, True]
print(li)

[1, 'a', 1.34, True]


## array定义

In [3]:
#将python的list转成数组

arr1 = np.array([1., 2, 3, 4])
# arr1 = np.array(range(1, 5))
print(arr1)

arr2 = np.array([1, "a", 3, 4])
print(arr2)

arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]])
print(arr3)

#多维list转成多维数组
arr4 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]],
                 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]]])
print(arr4)


[1. 2. 3. 4.]
['1' 'a' '3' '4']
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
[[[1 2 3 4]
  [5 6 7 8]
  [9 1 2 3]]

 [[1 2 3 4]
  [5 6 7 8]
  [9 1 2 3]]]


* 思考： python的list 和  numpy 的array  有什么区别？

1、list 数据结构，有相关的操作函数； numpy的array的话，更像是纯粹意义上的数组（可以是多维的）

## 查看数组结构

In [4]:
print(arr3.shape)
print(arr4.shape)

(3, 4)
(2, 3, 4)


## 查看数组类型

In [5]:
print(arr1.dtype)
print(arr2.dtype)  # 字节序，< 表示小端，> 表示大端，| 表示平台的字节序；11位的Unicode类型
print(arr4.dtype)

float64
<U21
int64


## 查看数组的大小

In [6]:
print(arr4.size)

24


## 更改数组的结构

In [7]:
print(arr3)
arr3.shape = (4, 3)
print(arr3)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [34]:
print(arr3.reshape((6, 2), order='F')) # order ='F' 按照fortan格式重新排列，也就是列优先顺序,变换后不共享内存'C'行优先，变换后共享内存；

arr33 = arr3.reshape((6,2), order='C')
print(arr3)
arr3[0][0] = 100
print(arr3)
print(arr33)


[[100   8]
 [  4   2]
 [  7   3]
 [  1   6]
 [  2   9]
 [  5   3]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [  1   2   3]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [  1   2   3]]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9   1]
 [  2   3]]


## arange函数

In [9]:
li1 = [0, 1, 2, 3, 4]
print(li1)
li2 = list(range(5)) #rang(stop) 产出[0,stop)之间的整数,步长1 只能是整数; 返回
print(li2)

aran1 = np.arange(5)
print(aran1)

aran2 = np.arange(1, 10, 0.5) #步长可以为小数
print(aran2)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0 1 2 3 4]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


## linspace函数——返回等差数组

In [10]:
arr5 = np.linspace(1, 10, 31) #产出1~10之间的数，产出31个值，公差d = （10-1)/(31-1)
print(arr5)
print(arr5.size)

[ 1.   1.3  1.6  1.9  2.2  2.5  2.8  3.1  3.4  3.7  4.   4.3  4.6  4.9
  5.2  5.5  5.8  6.1  6.4  6.7  7.   7.3  7.6  7.9  8.2  8.5  8.8  9.1
  9.4  9.7 10. ]
31


## logspace函数——返回等比数列

In [11]:
arr6 = np.logspace(1, 5, 5) # 生成1~5之间的数，总共5个，实际是等差数列；之后计算以base=10的指数
print(arr6)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


## 创建特殊的数组

In [13]:
arr7 = np.zeros((2, 3))
print(arr7)

arr8 = np.eye(4) ##斜对角线为1，单位矩阵
print(arr8)

arr9 = np.diag((2, 3, 4, 6))
print(arr9)

arr10 = np.ones((3, 4))
print(arr10)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 6]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 生成随机数

In [14]:
import random

print(random.random())  # 随机生成0-1之间的一个数
print(random.randint(2, 4))  # 随机生成2-4(含)之间的一个数
print(random.choice(["a", "b", "c"]))

print(np.random.random(10)) #生成一纬(这里是10个)0~1之间的数字
print(np.random.rand(2, 3, 4)) #生成2*3*4纬的0-1之间的数组
print(np.random.randn(2, 3))
print(np.random.randint(2, 5, size=(3, 4)))  # 不包含上限
print(np.random.choice(["a", "b", "c"], 2, replace=False))

0.15026308273653943
3
c
[0.60678943 0.45315675 0.8996228  0.11316797 0.16322611 0.3335705
 0.45953321 0.44851891 0.09492478 0.7773492 ]
[[[0.49568125 0.54270452 0.99298567 0.96478993]
  [0.5851713  0.46713199 0.77041779 0.7152846 ]
  [0.38202444 0.42881347 0.05603075 0.97346157]]

 [[0.94396458 0.7111687  0.01499701 0.54733916]
  [0.49282625 0.39252959 0.67939793 0.99739987]
  [0.97320911 0.51699703 0.04627957 0.13486135]]]
[[-0.30186922 -0.4497241  -0.07123355]
 [ 1.84620726 -0.56348851 -2.12896567]]
[[2 4 3 4]
 [4 2 2 4]
 [3 3 4 3]]
['a' 'b']


## 一维数组的索引和切片

In [15]:
a1 = np.arange(10)
print(a1)

print(a1[4])
print(a1[4:8])
print(type(a1[4:8]))

print(a1[-1])
print(a1[::-2])
print(a1[:])

[0 1 2 3 4 5 6 7 8 9]
4
[4 5 6 7]
<class 'numpy.ndarray'>
9
[9 7 5 3 1]
[0 1 2 3 4 5 6 7 8 9]


## 多维数组的索引和切片★

In [16]:
arr = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [7, 8, 9, 10, 11]])
# 索引的两种方式
print(arr[0][1])

print(arr[1, 2])

# 切片
print(arr[1][1:3])
print(arr[1, 1:3])

print(arr[1:3, 2:4])
print(arr[1:, 1:])
print(arr[1:3, 2:4])

2
6
[5 6]
[5 6]
[[ 6  7]
 [ 9 10]]
[[ 5  6  7  8]
 [ 8  9 10 11]]
[[ 6  7]
 [ 9 10]]


## 改变数组的形状

In [17]:
a2 = np.arange(12)
print(a2)

a3 = a2.reshape((3, 4))
print(a3)
print(a3.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [18]:
print(a3.ravel())
print(a3.flatten("C"))
print(a3.flatten("F"))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


## 数组的拼接

In [19]:
arr1 = np.arange(1, 7).reshape((3, 2))
arr2 = np.arange(11, 17).reshape((3, 2))
print(arr1)
print(arr2)

print(np.hstack((arr1, arr2)))
print(np.vstack((arr1, arr2)))

print(np.concatenate((arr1, arr2), axis=1))
print(np.concatenate((arr1, arr2), axis=0))

[[1 2]
 [3 4]
 [5 6]]
[[11 12]
 [13 14]
 [15 16]]
[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]
 [13 14]
 [15 16]]
[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]
 [13 14]
 [15 16]]


In [20]:
arr11 = np.arange(8).reshape((2, 4))
print(arr11)

print(np.hsplit(arr11, 2))
print(np.vsplit(arr11, 2))

print(np.split(arr11, 2, axis=1))
print(np.split(arr11, 2, axis=0))

[[0 1 2 3]
 [4 5 6 7]]
[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]
[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]


## np.any 、np.all

In [21]:
arr12 = np.array([True, True, False])
arr13 = np.array([True, True, True])
arr14 = np.array([False, False, False])

print(np.any(arr12))
print(np.any(arr14))

print(np.all(arr12))
print(np.all(arr13))

True
False
False
True


## 广播★

In [22]:
arr15 = np.arange(15).reshape((5, 3))
print(arr15)

arr16 = np.array([1, 2, 3])
print(arr15 + arr16)

arr17 = np.array([1, 2, 3])
print(arr15 + arr17)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]
 [13 15 17]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]
 [13 15 17]]


## 排序

In [23]:

arr21 = np.array([4, 3, 2])

print(sorted(arr21))  # 返回临时排序的列表
print(arr21)  # 原数组

print(arr21.argsort())  # 排序后的初始下标

[2, 3, 4]
[4 3 2]
[2 1 0]


In [24]:
arr21.sort()  # 不返回值，只进行排序操作
print(arr21)  # 排序后数组

[2 3 4]


## np.multiply（）、np.dot（）和星号（*）三种乘法运算的区别★

In [25]:
# np.multiply()函数
# 对应位置相乘，输出与相乘数组/矩阵的大小一致
arr_1 = np.array([[1, 2],
                  [3, 4]])
arr_2 = np.array([[5, 6],
                  [7, 8]])

np.multiply(arr_1, arr_2)

array([[ 5, 12],
       [21, 32]])

In [26]:
# np.dot()函数
# 对于秩为1的数组，执行对应位置相乘，然后再相加，可以理解为向量点积
arr_3 = np.array([0, 1, 2])
arr_4 = np.array([3, 2, 1])

np.dot(arr_3, arr_4)

4

In [27]:
# np.dot()函数
# 对于秩不为1的二维数组，执行矩阵乘法运算
arr_1 = np.array([[1, 2],
                  [3, 4]])
arr_2 = np.array([[5, 6],
                  [7, 8]])

np.dot(arr_1, arr_2)

array([[19, 22],
       [43, 50]])

In [28]:
# 星号（*）
# 对数组执行对应位置相乘
arr_1 * arr_2

array([[ 5, 12],
       [21, 32]])

## 几个重要的函数

In [29]:
# 几个重要函数
arr22 = np.array([3, 4, 2, 1, 1, 3, 2, 4])

print(np.unique(arr22))

[1 2 3 4]


In [30]:
print(np.tile(arr21, 5))

[2 3 4 2 3 4 2 3 4 2 3 4 2 3 4]


In [31]:
print(np.repeat(arr21, [3, 2, 1]))

[2 2 2 3 3 4]


In [32]:
arr23 = np.arange(6).reshape((2, 3))
print(arr23)
print(np.repeat(arr23, 2, axis=1))
print(np.repeat(arr23, 2, axis=0))

print(np.tile(arr23, 2))
print(np.tile(arr23, 2))

[[0 1 2]
 [3 4 5]]
[[0 0 1 1 2 2]
 [3 3 4 4 5 5]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [33]:
print(arr23.sum(axis=0))
print(arr23.mean())
print(arr23.std())
print(arr23.var())
print(arr23.argmax(axis=0))
print(arr23.argmin(axis=1))
print(arr23.cumsum())

[3 5 7]
2.5
1.707825127659933
2.9166666666666665
[1 1 1]
[0 0]
[ 0  1  3  6 10 15]
